[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-initialize-keyring",
  "allow-set-password",
  "allow-get-password", 
  "allow-set-secret",
  "allow-get-secret",
  "allow-delete-password",
  "allow-delete-secret",
  "allow-has-password",
  "allow-has-secret"
]
